modLoader="javafml"
loaderVersion="[45,)"
license="MIT"

[[mods]]
modId="mapfrontiers"
version="${version}"
displayName="MapPlayerList"
#updateJSONURL="https://alejandrocoria.games/projects/MapFrontiers/update.json"
displayURL="https://github.com/au5ton/MapPlayerList"
logoFile="logo.png"
credits="Adapted from MapFrontiers by Alejandro Coria."
authors="Austin Jackson (au5ton), Alejandro Coria (MemeSapiens)"
description='''
This mod is an addon for Journey Map that allows you to view the list of players logged into the server and jump to their position on the map.
'''

[[dependencies.mapfrontiers]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mapfrontiers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mapfrontiers]]
    modId="journeymap"
    mandatory=true
    versionRange="[1.19.4-5.9,)"
    ordering="NONE"
    side="BOTH"
